### ISSUE TITLE
Question: How would you partially update UI?

### ISSUE THREAD

**Issue by Malachiasz** [kaushikgopal/movies-usf#14]
I see that whenever there is a change in state you are setting all Views, Adapter anew. In my MVVM code I have LiveData object for small state chunks and I update them separate from each other. How would you achieve the same in MVI?

**Comment by jkaan** [comment]
Perhaps I could shed some light on this. I also work within an app that uses MVI as it's architecture and I do have some insights into this.

The entire idea of MVI and underlying the view state is that you don't do this. A view state would contain all of the information needed to render an entire screen, if you want to partially update the UI you would need to make sure that in the code that is handling the view state you would make sure to only handle the updated values. Simply that could mean checking if the same text is already set on a TextView for example (now the TextView itself has this capability already).

Of course the author might disagree :).

**Comment by Malachiasz** [comment]
At 44:40 @kaushikgopal  talks about this. https://fragmentedpodcast.com/episodes/151/ That solution is to emit always the whole state and use some diff tool in order not to update all UI elements which hasn't change in the state object. https://github.com/airbnb/epoxy lib should be helpfull here. But it seems quite big lib for me for this simple usecase. Or use DiffUtil. I don't get what he meant about distinctUntilChanged() operator. Perhaps that's already was about different topic.

**Comment by jkaan** [comment]
The `distinctUntilChanged` operator is to make sure that you are not outputting a view state that is 100% the same. Because that could mean that you are re-rendering things which are already in the exact same state.

**Comment by Malachiasz** [comment]
I see. It covers this case.

**Comment by kaushikgopal** [comment]
💯. looks like you folks got what i was saying (/trying to explain) :)

`distinctUntilChanged` merely handles one of the cases viz. preventing the re-setting of the exact same view state.

when the performance gain is noticeable and needed, one could use a variety of tools to selectively update the ui. `DiffTool`, `epoxy` etc. come in super handy for this. This is probably outside the scope of the underlying architecture that i'm trying to demonstrate here (but it does lend itself to the diffing possibility)
